let
  Source = Lakehouse.Contents(null){[workspaceId = "4a01221c-57e7-4a14-a63b-c696f1c5d5aa"]}[Data]{[lakehouseId = "7e9f824d-a2c3-4a35-8d41-7626423f5fd4"]}[Data],
  #"Navigation 1" = Source{[Id = "Files", ItemKind = "Folder"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "Landing"]}[Content],
  #"Navigation 3" = #"Navigation 2"{[Name = "WWI"]}[Content],
  Navigation = #"Navigation 3"{[Name = "dimension_customer.csv"]}[Content],
  #"Imported CSV" = Csv.Document(Navigation, [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
  #"Promoted headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"CustomerKey", Int64.Type}, {"WWICustomerID", Int64.Type}, {"Customer", type text}, {"BillToCustomer", type text}, {"Category", type text}, {"BuyingGroup", type text}, {"PrimaryContact", type text}, {"PostalCode", type text}, {"ValidFrom", type datetime}, {"ValidTo", type datetime}, {"LineageKey", Int64.Type}})
in
  #"Changed column type"